### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by applepeng** [wojciechk8/MMDVM_pog#2]
/tmp/ccANnA6K.s: Assembler messages:
/tmp/ccANnA6K.s:461: Warning: ignoring changed section attributes for .data
/tmp/cc8vlPEj.s: Assembler messages:
/tmp/cc8vlPEj.s:17: Warning: ignoring changed section attributes for .data
/tmp/ccMkS9xt.ltrans0.ltrans.o: In function `process':
/home/pi/MMDVM/SerialPort.cpp:670: undefined reference to `CSerialPort::availabl                                                                                        eForWriteInt(unsigned char)'
collect2: error: ld returned 1 exit status
Makefile.CMSIS:145: recipe for target 'bin/mmdvm.elf' failed
make: *** [bin/mmdvm.elf] Error 1

**Comment by wojciechk8** [comment]
Did you do all the steps described in "Building firmware"?
What is the command you're issuing to build the firmware?
I've just compiled the newest firmware without errors.

Regards
Wojciech

**Comment by applepeng** [comment]
sudo make -f Makefile.CMSIS

**Comment by N4IRS** [comment]
I just did a git clone of the MMDVM repository, added the STM32F4XX_Lib, edited Config.h and compiled with make -f Makefile.CMSIS. It compiled fine. I do have a script you can try that will setup the environment for you. it is at https://github.com/N4IRS/MMDVM-Install/tree/master/STM32-DVM. Maybe looking at the script can help you.

73, Steve N4IRS

**Comment by applepeng** [comment]
Thank you！

73 ， BH7NJF

**Comment by wojciechk8** [comment]
applepeng, the reason of compilation error was probably that you had enabled (uncommented) SERIAL_REPEATER option in config.h (it's not supported in MMDVM_pog board).

Regards,
Wojciech
