### ISSUE TITLE
Documentation ign pin

### ISSUE THREAD

**Issue by 2E0PGS** [wojciechk8/MMDVM_pog#4]
Hey great board however I cannot find out how the `IGN` pin is meant to be wired. 

I see there is two ign pins that appear to be connected via trace however I don't know if this pin needs to be held low with ground, held high with 3.3v or held high with 5v. 

If someone could clarify more detail on this it would be great.

I have figured out it's probably for car ignition? Because my PI wont boot with this hat ontop. I have to remove it before then add it once PI is booted which is not ideal.

Cheers,
2E0PGS

**Comment by wojciechk8** [comment]
> Hey great board however I cannot find out how the IGN pin is meant to be wired.

Thanks! The IGN pin is constantly connected to +5V. It refers to Ignition Sense in Motorola radios, which is used to turn on/off the radio. An example of application: when MMDVM is powered through raspberry pi, then resetting rPI causes also radio reset.

**Comment by 2E0PGS** [comment]
Any idea as to why my PI doesn't boot with the hat on top then?

It boots I remove it and add it post network interface lighting up.

Thanks for info on what the pin is for though. That's still useful.

⁣Cheers,
2E0PGS

**Comment by wojciechk8** [comment]
> Any idea as to why my PI doesn't boot with the hat on top then?

I don't know, maybe rPI is expecting a communication on USART during boot and it interferences with MMDVM.
